In [1]:
import pandas as pd

In [4]:
census = pd.read_csv('CENSUS DATA ACSDP5Y2018.DP05_data_with_overlays_2020-03-26T100029.csv')

In [5]:
covid = pd.read_csv('COVID-19 Data JHU 04-07-2020.csv')

In [11]:
unemployment = pd.read_csv('US State 2000 to present Unemployment Data 08Apr2020.csv')

In [8]:
census

,GEO_ID,NAME,DP05_0031PM,DP05_0032E,DP05_0032M,DP05_0032PE,DP05_0032PM,DP05_0033E,DP05_0033M,DP05_0033PE,...,DP05_0029M,DP05_0029PE,DP05_0029PM,DP05_0030E,DP05_0030M,DP05_0030PE,DP05_0030PM,DP05_0031E,DP05_0031M,DP05_0031PE
0,id,Geographic Area Name,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!RACE!!Total population,Margin of Error!!RACE!!Total population,Percent Estimate!!RACE!!Total population,...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...
1,0400000US01,Alabama,0.1,76.8,0.1,(X),(X),4864680,*****,4864680,...,626,783832,(X),340401,450,43.4,0.1,443431,395,56.6
2,0400000US02,Alaska,0.2,98.6,0.7,(X),(X),738516,*****,738516,...,317,78428,(X),38937,185,49.6,0.2,39491,226,50.4
3,0400000US04,Arizona,0.1,85.5,0.1,(X),(X),6946685,*****,6946685,...,305,1158320,(X),533914,210,46.1,0.1,624406,192,53.9
4,0400000US05,Arkansas,0.1,79.8,0.2,(X),(X),2990671,*****,2990671,...,716,487536,(X),216404,410,44.4,0.1,271132,540,55.6
5,0400000US06,California,0.1,79.7,0.1,(X),(X),39148760,*****,39148760,...,600,5315457,(X),2357611,429,44.4,0.1,2957846,433,55.6
6,0400000US08,Colorado,0.1,83.9,0.1,(X),(X),5531141,*****,5531141,...,523,740638,(X),337916,413,45.6,0.1,402722,370,54.4
7,0400000US09,Connecticut,0.1,76.2,0.1,(X),(X),3581504,*****,3581504,...,234,587580,(X),254027,154,43.2,0.1,333553,152,56.8
8,0400000US10,Delaware,0.1,80.3,0.1,(X),(X),949495,*****,949495,...,49,167129,(X),74446,47,44.5,0.1,92683,11,55.5
9,0400000US11,District of Columbia,0.1,69.1,0.2,(X),(X),684498,*****,684498,...,90,81712,(X),33378,62,40.8,0.1,48334,65,59.2
10,0400000US12,Florida,0.1,82.0,0.1,(X),(X),20598139,*****,20598139,...,869,4064376,(X),1831450,651,45.1,0.1,2232926,559,54.9
11,0400000US13,Georgia,0.1,76.7,0.1,(X),(X),10297484,*****,10297484,...,1108,1352289,(X),587115,815,43.4,0.1,765174,823,56.6
12,0400000US15,Hawaii,0.1,82.5,0.1,(X),(X),1422029,*****,1422029,...,130,245955,(X),111178,82,45.2,0.1,134777,96,54.8
13,0400000US16,Idaho,0.1,89.5,0.4,(X),(X),1687809,*****,1687809,...,493,253801,(X),119895,398,47.2,0.1,133906,352,52.8
14,0400000US17,Illinois,0.1,76.6,0.1,(X),(X),12821497,*****,12821497,...,813,1894903,(X),821647,541,43.4,0.1,1073256,453,56.6
15,0400000US18,Indiana,0.1,78.0,0.1,(X),(X),6637426,*****,6637426,...,852,996063,(X),436467,490,43.8,0.1,559596,636,56.2
16,0400000US19,Iowa,0.1,79.5,0.2,(X),(X),3132499,*****,3132499,...,457,513312,(X),227340,344,44.3,0.1,285972,324,55.7
17,0400000US20,Kansas,0.1,80.3,0.2,(X),(X),2908776,*****,2908776,...,552,437777,(X),195027,411,44.5,0.1,242750,391,55.5
18,0400000US21,Kentucky,0.1,78.7,0.2,(X),(X),4440204,*****,4440204,...,727,691509,(X),304481,492,44.0,0.1,387028,578,56.0
19,0400000US22,Louisiana,0.1,77.7,0.1,(X),(X),4663616,*****,4663616,...,605,676707,(X),295906,441,43.7,0.1,380801,381,56.3
20,0400000US23,Maine,0.1,82.9,0.2,(X),(X),1332813,*****,1332813,...,284,259176,(X),117451,187,45.3,0.1,141725,201,54.7
21,0400000US24,Maryland,0.1,76.0,0.1,(X),(X),6003435,*****,6003435,...,393,875337,(X),377866,255,43.2,0.1,497471,257,56.8
22,0400000US25,Massachusetts,0.1,75.7,0.1,(X),(X),6830193,*****,6830193,...,312,1078224,(X),464595,215,43.1,0.1,613629,305,56.9
23,0400000US26,Michigan,0.1,80.0,0.1,(X),(X),9957488,*****,9957488,...,520,1620944,(X),720494,371,44.4,0.1,900450,361,55.6
24,0400000US27,Minnesota,0.1,82.1,0.1,(X),(X),5527358,*****,5527358,...,442,830112,(X),374196,321,45.1,0.1,455916,316,54.9
25,0400000US28,Mississippi,0.1,76.3,0.2,(X),(X),2988762,*****,2988762,...,683,449478,(X),194579,407,43.3,0.1,254899,528,56.7
26,0400000US29,Missouri,0.1,78.4,0.1,(X),(X),6090062,*****,6090062,...,798,981692,(X),431416,525,43.9,0.1,550276,605,56.1
27,0400000US30,Montana,0.1,91.5,0.4,(X),(X),1041732,*****,1041732,...,376,183823,(X),87835,256,47.8,0.1,95988,281,52.2
28,0400000US31,Nebraska,0.1,80.5,0.2,(X),(X),1904760,*****,1904760,...,317,286080,(X),127624,239,44.6,0.1,158456,251,55.4
29,0400000US32,Nevada,0.1,89.9,0.1,(X),(X),2922849,*****,2922849,...,357,438051,(X),207437,242,47.4,0.1,230614,196,52.6
30,0400000US33,New Hampshire,0.1,83.7,0.2,(X),(X),1343622,*****,1343622,...,303,227984,(X),103902,209,45.6,0.1,124082,223,54.4
31,0400000US34,New Jersey,0.1,74.8,0.1,(X),(X),8881845,*****,8881845,...,287,1376863,(X),589327,178,42.8,0.1,787536,255,57.2
32,0400000US35,New Mexico,0.1,83.8,0.2,(X),(X),2092434,*****,2092434,...,415,341515,(X),155724,234,45.6,0.1,185791,355,54.4
33,0400000US36,New York,0.1,74.5,0.1,(X),(X),19618453,*****,19618453,...,572,3068689,(X),1309870,401,42.7,0.1,1758819,390,57.3
34,0400000US37,North Carolina,0.1,77.3,0.1,(X),(X),10155624,*****,10155624,...,749,1570998,(X),685104,600,43.6,0.1,885894,653,56.4
35,0400000US38,North Dakota,0.1,83.0,0.5,(X),(X),752201,*****,752201,...,283,109910,(X),49865,176,45.4,0.1,60045,235,54.6
36,0400000US39,Ohio,0.1,77.3,0.1,(X),(X),11641879,*****,11641879,...,798,1892861,(X),825233,541,43.6,0.1,1067628,526,56.4
37,0400000US40,Oklahoma,0.1,80.1,0.1,(X),(X),3918137,*****,3918137,...,485,589230,(X),262107,329,44.5,0.1,327123,311,55.5
38,0400000US41,Oregon,0.1,84.1,0.1,(X),(X),4081943,*****,4081943,...,483,682546,(X),311769,357,45.7,0.1,370777,358,54.3
39,0400000US42,Pennsylvania,0.1,76.7,0.1,(X),(X),12791181,*****,12791181,...,629,2229861,(X),968078,392,43.4,0.1,1261783,411,56.6
40,0400000US44,Rhode Island,0.1,75.0,0.2,(X),(X),1056611,*****,1056611,...,303,174210,(X),74646,194,42.8,0.1,99564,183,57.2
41,0400000US45,South Carolina,0.1,79.8,0.1,(X),(X),4955925,*****,4955925,...,490,829083,(X),367881,318,44.4,0.1,461202,399,55.6
42,0400000US46,South Dakota,0.1,84.6,0.4,(X),(X),864289,*****,864289,...,343,136808,(X),62706,213,45.8,0.1,74102,240,54.2
43,0400000US47,Tennessee,0.1,78.8,0.1,(X),(X),6651089,*****,6651089,...,789,1045213,(X),460702,574,44.1,0.1,584511,581,55.9
44,0400000US48,Texas,0.1,80.2,0.1,(X),(X),27885195,*****,27885195,...,1144,3337814,(X),1485374,786,44.5,0.1,1852440,844,55.5
45,0400000US49,Utah,0.1,86.0,0.2,(X),(X),3045350,*****,3045350,...,371,320269,(X),148095,217,46.2,0.1,172174,271,53.8
46,0400000US50,Vermont,0.1,84.0,0.3,(X),(X),624977,*****,624977,...,246,113550,(X),51847,146,45.7,0.1,61703,192,54.3
47,0400000US51,Virginia,0.1,79.2,0.1,(X),(X),8413774,*****,8413774,...,704,1230246,(X),543810,552,44.2,0.1,686436,563,55.8
48,0400000US53,Washington,0.1,83.7,0.1,(X),(X),7294336,*****,7294336,...,519,1073499,(X),489026,337,45.6,0.1,584473,398,54.4
49,0400000US54,West Virginia,0.1,82.4,0.3,(X),(X),1829054,*****,1829054,...,575,344719,(X),155721,392,45.2,0.1,188998,385,54.8
50,0400000US55,Wisconsin,0.1,82.4,0.1,(X),(X),5778394,*****,5778394,...,475,924695,(X),417760,337,45.2,0.1,506935,348,54.8
51,0400000US56,Wyoming,0.2,90.6,0.6,(X),(X),581836,*****,581836,...,302,87777,(X),41720,194,47.5,0.2,46057,228,52.5
52,0400000US72,Puerto Rico,*****,77.0,*****,(X),(X),3386941,*****,3386941,...,*****,640623,(X),278729,*****,43.5,*****,361894,*****,56.5

In [12]:
unemployment

,State Weekly Claims for Unemplyment Insurance Data Not Seasonally Adjusted,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,State,Filed week ended,Initial Claims,Reflecting Week Ended,Continued Claims,Covered Employment,Insured Unemployment Rate,NaN,NaN,NaN
4,Alabama,1/1/2000,"10,099",12/25/1999,"33,472","1,806,088",1.85,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
55969,Wyoming,3/7/2020,534,2/29/2020,"3,508","268,518",1.31,NaN,NaN,NaN
55970,Wyoming,3/14/2020,517,3/7/2020,"3,375","268,518",1.26,NaN,NaN,NaN
55971,Wyoming,3/21/2020,"3,653",3/14/2020,"3,197","268,518",1.19,NaN,NaN,NaN
55972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55973,Run Date: 4/8/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
covid

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-07 23:04:49,34.223334,-82.461707,5,0,0,0,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-07 23:04:49,30.295065,-92.414197,82,2,0,0,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-07 23:04:49,37.767072,-75.632346,11,0,0,0,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-07 23:04:49,43.452658,-116.241552,419,3,0,0,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-07 23:04:49,41.330756,-94.471059,1,0,0,0,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2852,NaN,NaN,NaN,Vietnam,2020-04-07 23:04:29,14.058324,108.277199,249,0,123,126,Vietnam
2853,NaN,NaN,NaN,West Bank and Gaza,2020-04-07 23:04:29,31.952200,35.233200,261,1,42,218,West Bank and Gaza
2854,NaN,NaN,NaN,Western Sahara,2020-04-07 23:04:29,24.215500,-12.885800,4,0,0,4,",,Western Sahara"
2855,NaN,NaN,NaN,Zambia,2020-04-07 23:04:29,-13.133897,27.849332,39,1,7,31,Zambia
2856,NaN,NaN,NaN,Zimbabwe,2020-04-07 23:04:29,-19.015438,29.154857,11,2,0,9,Zimbabwe